import lib.filter_column as fc

""" Handles updated 119 input variables of the SEER*Stat Matrix files. Also shows removed entries for completeness. """
data_pipeline_full = [

    # Categorical inputs:
    ('Marital status at diagnosis', [], [], 'categorical'),
    ('Race/ethnicity', [], [], 'categorical'),
    ('Sex', [], [], 'categorical'),
    ('Primary Site', [], [], 'categorical'),
    ('Laterality', [], [], 'categorical'),
    ('Histologic Type ICD-O-3', [], [], 'categorical'),
    ('Behavior code ICD-O-3', [], [], 'categorical'),
    ('Grade Recode (thru 2017)', [], [], 'categorical'),
    ('Type of Reporting Source', [], [], 'categorical'),
    ('EOD 10 - size (1988-2003)', [], [], 'categorical'),
    ('EOD 10 - extent (1988-2003)', [], [], 'categorical'),
    ('EOD 10 - Prostate path ext (1988-2003)', [], [], 'categorical'),
    ('EOD 10 - nodes (1988-2003)', [], [], 'categorical'),
    ('Coding system-EOD (1973-2003)', [], [], 'categorical'),
    ('Tumor marker 1 (1990-2003)', [], [], 'categorical'),
    ('Tumor marker 2 (1990-2003)', [], [], 'categorical'),
    ('Tumor marker 3 (1990-2003)', [], [], 'categorical'),
    ('CS extension (2004-2015)', [], [], 'categorical'),
    ('CS lymph nodes (2004-2015)', [], [], 'categorical'),
    ('CS mets at dx (2004-2015)', [], [], 'categorical'),
    ('CS site-specific factor 1 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 2 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 3 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 4 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 5 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 6 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 25 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('Derived AJCC T, 6th ed (2004-2015)', [], [], 'categorical'),
    ('Derived AJCC N, 6th ed (2004-2015)', [], [], 'categorical'),
    ('Derived AJCC M, 6th ed (2004-2015)', [], [], 'categorical'),
    ('Derived AJCC Stage Group, 6th ed (2004-2015)', [], [], 'categorical'),
    ('SEER Combined Summary Stage 2000 (2004-2017)', [], [], 'categorical'),
    ('CS version input original (2004-2015)', [], [], 'categorical'),
    ('CS version derived (2004-2015)', [], [], 'categorical'),
    ('CS version input current (2004-2015)', [], [], 'categorical'),
    ('Site recode ICD-O-3/WHO 2008', [], [], 'categorical'),
    ('ICCC site recode 3rd edition/IARC 2017', [], [], 'categorical'),
    ('ICCC site recode extended 3rd edition/IARC 2017', [], [], 'categorical'),
    ('Behavior recode for analysis', [], [], 'categorical'),
    ('Histology recode - broad groupings', [], [], 'categorical'),
    ('SEER Brain and CNS Recode', [], [], 'categorical'),
    ('TNM 7/CS v0204+ Schema (thru 2017)', [], [], 'categorical'),
    ('Race recode (White, Black, Other)', [], [], 'categorical'),
    ('Race recode (W, B, AI, API)', [], [], 'categorical'),
    ('Origin recode NHIA (Hispanic, Non-Hisp)', [], [], 'categorical'),
    ('SEER historic stage A (1973-2015)', [], [], 'categorical'),
    ('AJCC stage 3rd edition (1988-2003)', [], [], 'categorical'),
    ('SEER modified AJCC stage 3rd (1988-2003)', [], [], 'categorical'),
    ('Combined Summary Stage (2004+)', [], [], 'categorical'),
    ('First malignant primary indicator', [], [], 'categorical'),
    ('IHS link', [], [], 'categorical'),
    ('Summary stage 2000 (1998-2017)', [], [], 'categorical'),
    ('AYA site recode 2020 Revision', [], [], 'categorical'),
    ('Lymphoid neoplasm recode 2021 Revision', [], [], 'categorical'),
    ('Primary by international rules', [], [], 'categorical'),
    ('ER Status Recode Breast Cancer (1990+)', [], [], 'categorical'),
    ('PR Status Recode Breast Cancer (1990+)', [], [], 'categorical'),
    ('CS Schema - AJCC 6th Edition', [], [], 'categorical'),
    ('CS site-specific factor 8 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 10 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 11 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 13 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 15 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 16 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('Lymph-vascular Invasion (2004+ varying by schema)', [], [], 'categorical'),
    ('Derived AJCC T 7th ed (2010-2015)', [], [], 'categorical'),
    ('Derived AJCC N 7th ed (2010-2015)', [], [], 'categorical'),
    ('Derived AJCC M 7th ed (2010-2015)', [], [], 'categorical'),
    ('Derived AJCC Stage Group, 7th ed (2010-2015)', [], [], 'categorical'),
    ('Breast - Adjusted AJCC 6th T (1988-2015)', [], [], 'categorical'),
    ('Breast - Adjusted AJCC 6th N (1988-2015)', [], [], 'categorical'),
    ('Breast - Adjusted AJCC 6th M (1988-2015)', [], [], 'categorical'),
    ('Breast - Adjusted AJCC 6th Stage (1988-2015)', [], [], 'categorical'),
    ('Adjusted CS site-specific factor 7 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 9 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('CS site-specific factor 12 (2004-2017 varying by schema)', [], [], 'categorical'),
    ('Derived HER2 Recode (2010+)', [], [], 'categorical'),
    ('Breast Subtype (2010+)', [], [], 'categorical'),
    ('Lymphoma - Ann Arbor Stage (1983-2015)', [], [], 'categorical'),
    ('SEER Combined Mets at DX-bone (2010+)', [], [], 'categorical'),
    ('SEER Combined Mets at DX-brain (2010+)', [], [], 'categorical'),
    ('SEER Combined Mets at DX-liver (2010+)', [], [], 'categorical'),
    ('SEER Combined Mets at DX-lung (2010+)', [], [], 'categorical'),
    ('T value - based on AJCC 3rd (1988-2003)', [], [], 'categorical'),
    ('N value - based on AJCC 3rd (1988-2003)', [], [], 'categorical'),
    ('M value - based on AJCC 3rd (1988-2003)', [], [], 'categorical'),
    ('Median household income inflation adj to 2022', [], [], 'categorical'),
    ('Rural-Urban Continuum Code', [], [], 'categorical'),

    # Numerical inputs
    # If 1-n encoding used, encode special codes (unknown, empty) as distinct 1-n vector
    # Encode empty (-1) for all continuous and special codes depending on the variable (see SEER data dictionary)
    ('Age recode with single ages and 90+', [(fc.encode_values, [[-1, 999]])], [], 'continuous'),
    ('Year of birth', [(fc.encode_values, [[-1]])], [], 'continuous'),
    ('Year of diagnosis', [(fc.encode_values, [[-1]])], [], 'continuous'),

    ('Regional nodes positive (1988+)', [(fc.encode_values, [[-1, 90, 95, 97, 98, 99]])], [], 'continuous'),
    ('Regional nodes examined (1988+)', [(fc.encode_values, [[-1, 90, 95, 96, 97, 98, 99]])], [], 'continuous'),
    ('CS tumor size (2004-2015)', [(fc.encode_values, [[-1, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 888]])], [],
     'continuous'),
    ('Age recode with <1 year olds', [(fc.encode_values, [[-1, 99]])], [], 'continuous'),

    # Modified Inputs:
    # Remove info if more than one primary, not applicable for experiments
    ('Sequence number', [(fc.map_values, [{0: 1, 60: 61}])], [], 'categorical'),

    # Target relevant inputs - will be transformed into the target later
    ('SEER cause-specific death classification', [], [], 'target'),
    ('Survival months', [], [], 'target'),

    # Removed due to irrelevancy:
    ('Patient ID', [], [], 'remove'),
    ('Survival months flag', [], [], 'remove'),
    ('Record number recode', [], [], 'remove'),

    # Removed due to information added after diagnosis:
    # might contain information about a confirmation after the initial diagnosis.
    ('Diagnostic Confirmation', [], [], 'remove'),
    ('COD to site recode', [], [], 'remove'),
    ('SEER other cause of death classification', [], [], 'remove'),
    ('COD to site rec KM', [], [], 'remove'),
    ('Vital status recode (study cutoff used)', [], [], 'remove'),
    ('Total number of in situ/malignant tumors for patient', [], [], 'remove'),
    ('Total number of benign/borderline tumors for patient', [], [], 'remove'),

    # Removed due to treatment information:
    ('RX Summ--Surg Prim Site (1998+)', [], [], 'remove'),
    ('RX Summ--Scope Reg LN Sur (2003+)', [], [], 'remove'),
    ('RX Summ--Surg Oth Reg/Dis (2003+)', [], [], 'remove'),
    ('RX Summ--Reg LN Examined (1998-2002)', [], [], 'remove'),
    ('Reason no cancer-directed surgery', [], [], 'remove'),
    ('Site specific surgery (1973-1997 varying detail by year and site)', [], [], 'remove'),
    ('Scope of reg lymph nd surg (1998-2002)', [], [], 'remove'),
    ('Surgery of oth reg/dis sites (1998-2002)', [], [], 'remove'),
    ('CS Tumor Size/Ext Eval (2004-2015)', [], [], 'remove'),
    ('CS Reg Node Eval (2004-2015)', [], [], 'remove'),
    ('CS Mets Eval (2004-2015)', [], [], 'remove')
]
